apiVersion: v1
kind: Service
metadata:
  labels:
    app: chaincode-adapter
  name: chaincode-adapter
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: chaincode-adapter
